### ISSUE TITLE
Can't reproduce videos with Expo AV using the UT provided URL

### ISSUE THREAD

**Issue by bmarianome** [pingdotgg/uploadthing#558] opened 2024-01-17 14:25 UTC
### I understand that this issue may be closed if it should be filed in another category

- [x] I understand

### My issue

Hi, I'm trying to reproduce a video uploaded to UploadThing in an Expo App using the `expo-av` package.

The video doesn't show and I get the following error: 
```
The server is not correctly configured. - The AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain".
```

This only occurs with a video uploaded to UT. I already tried with a raw public S3 bucket, and many other sources, and it works.

Steps to reproduce:
1) Create an expo app with `npx create-expo-app my-app`
2) Install the expo-av package with `npm install expo-av`, 
3) Run the dev server with `npx expo start` 
4) Use the component anywhere in the app: 
```
import * as React from "react";
import { View } from "react-native";
import { Video, ResizeMode } from "expo-av";

export default function VideoComponent() {
  const video = React.useRef(null);
  return (
    <View className="w-full aspect-video">
      <Video
        ref={video}
        source={{
          uri: "https://utfs.io/f/de73ba7a-29b4-4c27-a7fd-a47005b1377a-1rrszn.mp4",
        }}
        useNativeControls
        resizeMode={ResizeMode.CONTAIN}
        className="w-full h-full rounded-lg bg-gray-100"
        onError={(e) => console.log("error", e)}
      />
    </View>
  );
}
```
I'm using the NativeWind package to style the components, to use the default styles you can find an example in: https://docs.expo.dev/versions/latest/sdk/video. Remember to use an URL of a video uploaded to UT, like so: https://utfs.io/f/de73ba7a-29b4-4c27-a7fd-a47005b1377a-1rrszn.mp4

**Comment by markflorkowski** [comment] 2024-01-17 20:49
Looking into this, my guess is that this has to do with requesting "chunks" of the file, and our proxy isn't handling that correctly, but so far this has been very difficult to debug, since I can't seem to see the requests that are being made anywhere

**Comment by ahmad1702** [comment] 2024-01-17 21:45
@markflorkowski, it might be specific to how iOS accepts video files. Sometimes it rejects if a server doesn't add metadata such as `Content-range.` This [react-native-video](https://github.com/react-native-video/react-native-video/issues/2859#issuecomment-1258778105) issue sums it up quite well.

**Comment by markflorkowski** [comment] 2024-01-17 23:40
That was super helpful! We were able to find a pretty simple fix, will get that up later today and let you know when it is out 👍

**Comment by markflorkowski** [comment] 2024-01-18 00:52
Fix has been deployed!

**Comment by markflorkowski** [comment] 2024-01-18 01:00
Hmm it seems like the fix is not working the same way that it was in dev

**Comment by ahmad1702** [comment] 2024-01-18 17:36
Ah, unfortunate, is there an easy way to reproduce it? I can run a test of uploadthing on an expo project I'm working on and see what happens

**Comment by markflorkowski** [comment] 2024-01-18 20:15
It looks like we may have found the solution to this, fix should be up later today

**Comment by markflorkowski** [comment] 2024-01-18 20:55
Ok, fix is up for real this time, and I have confirmed it works correctly this time 😅

**Closed by markflorkowski** 2024-01-18 20:55 UTC
Labels: 🐛 bug: unconfirmed

**Comment by bmarianome** [comment] 2024-01-18 21:20
Thank you @markflorkowski
