### ISSUE TITLE
[Bug]: Landing Page Doesn't Look Right on Smaller Screens

### ISSUE THREAD

**Issue by peterkibuchi** [pingdotgg/uploadthing#107] opened 2023-05-27 02:42 UTC
### What happened?

On smaller screen sizes the banner text isn't (vertically) centered and the background gradient doesn't cover the whole screen:

![Screenshot from 2023-05-27 05-19-12](https://github.com/pingdotgg/uploadthing/assets/68213317/fc58a71d-6cfe-4560-b25b-c2593d933695)

![Screenshot from 2023-05-27 05-19-55](https://github.com/pingdotgg/uploadthing/assets/68213317/6ef8ce3c-6dcf-4b41-9b68-af774ee4eb24)

I created a fork so I could submit a PR but couldn't find the code for the site; it would seem that it doesn't live here.

I realize that this may not be a high priority issue, but thought it necessary to bring it to your attention, in case you weren't aware of it.

### What did you expect to happen?

Ummm, for the banner text to be vertically centered and the background gradient to cover the entire background I guess? :)

### Version

N/A

### Reproduction Steps

Visit uploadthing's home page. Hit `ctrl +` to simulate a smaller screen.

### Reproduction Repository

N/A

### Relevant log output

```bash
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment] 2023-05-27 19:33
Should be fixed now -- duplicate of #96

**Closed by markflorkowski** 2023-05-27 19:33 UTC
