### ISSUE TITLE
Brave broser performance issues

### ISSUE THREAD

**Issue by varto1488** [pingdotgg/uploadthing#187] opened 2023-06-27 00:01 UTC
### What happened?

When I use brave browser app becomes extremely slow as a guest user which is strange without even logging in just sitting in the performance page, not sure why tried to do lighthouse /performance tab tests but too laggy to even click there.

I see some errors not sure if this helps...

<img width="1238" alt="Screenshot 2023-06-27 at 00 33 46" src="https://github.com/pingdotgg/uploadthing/assets/7349374/b5750e44-4bc9-444a-95f9-d09de6f47471">
<img width="610" alt="Screenshot 2023-06-27 at 00 17 34" src="https://github.com/pingdotgg/uploadthing/assets/7349374/33742658-662f-467c-a241-5a2a76f46702">

### What did you expect to happen?

I would expect to browse the home page/pricing page without performance being laggy 

### Version

Brave browser [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)](https://brave.com/latest/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment] 2023-06-27 00:32
huh, odd. Can't repro on arc, downloading brave to try now, but it really shouldn't matter, since they're both chromium based. Does it make any difference if you are logged in vs not?

**Comment by markflorkowski** [comment] 2023-06-27 00:36
Can't repro on brave either, I think this may be due to some extension or configuration on your end.

**Comment by varto1488** [comment] 2023-06-27 01:01
Not sure what could be I removed most of my extensions, I have youtube playing, and I get those errors when resizing page to mobile and then back to desktop. But performance are laggy without resizing. Btw Chrome works fine for me

**Comment by markflorkowski** [comment] 2023-06-27 03:17
I'll give it another shot tomorrow to see if I can manage to reproduce this behaviour. Would you mind attaching a screen recording of what you're seeing, as well as a screenshot of activity monitor?

**Comment by markflorkowski** [comment] 2023-06-28 20:10
I have not been able to reproduce this issue, closing for now, but if you are able to provide consistent repro steps, feel free to  re-open.

**Closed by markflorkowski** 2023-06-28 20:10 UTC
Labels: Needs repro
