### ISSUE TITLE
can't upload file

### ISSUE THREAD

**Issue by developertomek** [pingdotgg/uploadthing#367] opened 2023-09-18 10:33 UTC
I copied everything from the documentation one by one, midleware, API route, components, and example and I can not upload file because I have error.

In console 
![fileinconsolelog](https://github.com/pingdotgg/uploadthing/assets/32014965/a7faf83e-6ea5-4b39-b15e-faa50c44caeb)

Request URL: http://localhost:3000/api/uploadthing?actionType=upload&slug=imageUploader
Request Method: POST
Status Code: 500 Internal Server Error

<code>"[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.json (/.../node_modules/uploadthing/dist/next-legacy.js:600:16)</code>
    
    
<code>Error: Something went wrong. Please report this to UploadThing.
    at fatalClientError (chunk-CKIYT4XT.mjs:104:1)
    at eval (chunk-CKIYT4XT.mjs:148:52)</code>

**Comment by A-AllaaEddine** [comment] 2023-09-18 11:50
Same here! I thought i did something while configuring it but i see that it's not the case.

**Comment by Mr0Bread** [comment] 2023-09-18 12:28
What version of UploadThing are you using?

**Comment by A-AllaaEddine** [comment] 2023-09-18 12:32
Latest ver @5.6.0.

**Comment by Mr0Bread** [comment] 2023-09-18 16:49
Can you provide a repo where the issue can be reproduced?

**Comment by juliusmarminge** [comment] 2023-09-18 18:45
Can you try 

pnpm add uploadthing@5.6.1-canary.baa2a0e

**Comment by markflorkowski** [comment] 2023-09-18 18:49
Just tested swapping it in the repo you linked, and it looks like it worked. Going to cut a release now so you don't need to use a canary

**Comment by markflorkowski** [comment] 2023-09-18 18:53
`uploadthing@5.6.1` which includes the fix for this bug is now up. Feel free to re-open if for some reason it is not working for you!

**Closed by markflorkowski** 2023-09-18 18:53 UTC
