### ISSUE TITLE
[Bug]: selecting same file twice breaks dropzone

### ISSUE THREAD

**Issue by CyanFlare** [pingdotgg/uploadthing#933] opened 2024-09-08 20:32 UTC
### What happened?

When selecting the same file twice and removing one of them it will revert the dropzone back to its empty state but will still have the remaining file at the top and become unremovable.

https://github.com/user-attachments/assets/adbf2e57-4456-4f1b-93a6-eb05c9e97f83

### What did you expect to happen?

Removing one of the files should not throw me back to the empty view and should allow me to remove the remaining duplicate file.

### Version

N/A

### Reproduction Steps

1. select file to upload
2. select same file to upload
3. remove one of the files
4. try removing remaining file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment] 2024-09-09 19:03
How did you manage to get it to select the same file twice? When I try to reproduce this, it does not add the file the second time. (both with selecting, and with drag and drop) 

Can you share what browser/os you are using?

**Comment by CyanFlare** [comment] 2024-09-09 19:35
> Can you share what browser/os you are using?

I'm on Windows 11 and using Chrome v128.0.6613.120

**Comment by markflorkowski** [comment] 2024-09-09 19:57
Ok, just confirmed, this seems to be a Chrome-specific bug. 

Was able to repro on both MacOS and Windows using the latest release of Chrome. Will investigate further to see what we can do about it!

Thanks for the report 👍

**Comment by C-W-D-Harshit** [comment] 2024-09-15 12:53
Is this issue resolved? If not, you can assign it to me!

**Comment by markflorkowski** [comment] 2024-09-15 17:14
@C-W-D-Harshit - Unfortunately, this issue is with the dashboard, which is not part of the OSS repo. Appreciate the offer though!

**Comment by juliusmarminge** [comment] 2024-09-16 09:02
I cannot reproduce this on latest macOS and Chrome with the recent dashboard update. Can anyone confirm this is resolved?

**Comment by CyanFlare** [comment] 2024-09-16 15:21
> I cannot reproduce this on latest macOS and Chrome with the recent dashboard update. Can anyone confirm this is resolved?

Seems like it has been resolved. I'm no longer able to upload 2 of the same file.

**Closed** 2024-09-16 15:43 UTC
Labels: bug: medium priority, area:dashboard
