### ISSUE TITLE
[Bug]: My stiles are broken

### ISSUE THREAD

**Issue by Pablussss** [pingdotgg/uploadthing#386] opened 2023-09-24 08:37 UTC
### What happened?

When I apply uploadthing styles to my code, they break my styles. I have read the documentation and followed the recommendations. In my layout.tsx I declare them in the following order:
```
import "@uploadthing/react/styles.css";
import "./globals.css";
```

What breaks is that it hides my navbar, which is made with [shadcn ](https://ui.shadcn.com/) this has a "hidden" style for when it is being displayed on non-mobile devices, that is, I have a navbar for mobile and another for desktop:
- Navbar that is not visible: `<div className="mr-4 hidden sm:flex">`.

If I remove the uploadthing styles, the navbar works normally. Also in my tailwind.conf.ts I have withUt added as recommended in the documentation:

```
import {withUt} from "uploadthing/tw";

module.exports = withUt({})
```

### What did you expect to happen?

Styles should display normally, showing the navbar.

With uploadthing styles:
![image](https://github.com/pingdotgg/uploadthing/assets/69087295/14d3daef-0cd6-4667-bf79-7d7147d910a2)

Without uploadthing styles:
![image](https://github.com/pingdotgg/uploadthing/assets/69087295/71963959-abe5-4daa-8af3-3933aed665d7)

### Version

My package.json:
```
"next": "13.5.2",
"@uploadthing/react": "5.6.1",
"uploadthing": "5.6.1",
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr0Bread** [comment] 2023-09-24 08:38
Are you on latest version?

**Comment by Pablussss** [comment] 2023-09-24 17:22
> Are you on latest version?

Yes, I have uploadthing on the lastest (5.6.1) and next on (13.5.2)

**Comment by juliusmarminge** [comment] 2023-09-24 18:08
We have a canary out fixing some stuff with the `withUt` function. 

```sh
pnpm add uploadthing@5.6.2-canary.acce8fd
```

This will be released in the next version

**Comment by Pablussss** [comment] 2023-09-25 10:12
> We have a canary out fixing some stuff with the `withUt` function.
> 
> ```shell
> pnpm add uploadthing@5.6.2-canary.acce8fd
> ```
> 
> This will be released in the next version

Still not working, so I have to wait for the next version?

**Comment by markflorkowski** [comment] 2023-09-25 22:38
Are you able to share a reproduction of this so we can debug further?

**Comment by AntonioErdeljac** [comment] 2023-09-26 09:51
I can confirm that I get this in the newest versions of UploadThing. What works for me is to move uploadthing CSS into the globals.css end of the file. This is an example: https://github.com/AntonioErdeljac/next13-discord-clone/issues/18#issuecomment-1720244154

**Comment by Pablussss** [comment] 2023-09-26 17:06
> Are you able to share a reproduction of this so we can debug further?

Its a big project, but I tried to make a little reproduction here, it works on my computer and has the same bug so try it.

[project](https://stackblitz.com/edit/stackblitz-starters-jip31y?file=README.md)

**Comment by Pablussss** [comment] 2023-09-26 17:09
> I can confirm that I get this in the newest versions of UploadThing. What works for me is to move uploadthing CSS into the globals.css end of the file. This is an example: [AntonioErdeljac/next13-discord-clone#18 (comment)](https://github.com/AntonioErdeljac/next13-discord-clone/issues/18#issuecomment-1720244154)

seems that works, thanks!

**Comment by markflorkowski** [comment] 2023-09-26 18:58
If you are using the `withUt()` helper, you do not need to (and should not) add any import for the uploadthing styles. You should only have one or the other.

**Closed** 2023-09-26 19:31 UTC
Labels: bug, area:packages
