### ISSUE TITLE
feat: Search by key in web UI

### ISSUE THREAD

**Issue by devklepacki** [pingdotgg/uploadthing#1083] opened 2024-12-04 13:03 UTC
### Describe the feature you'd like to request

Please for the love of God, allow searching by file key in the Files table in web UI. Currently, the search is only working by name.

The use case: sometimes on my website I have a picture I'd like to remove. Without the option to search by key, it's not possible to just inspect the element & copy it's key, and simply remove the file with UT web UI.

### Describe the solution you'd like to see

Search should search by keys as well as file names

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment] 2024-12-04 18:21
Duplicate of https://github.com/pingdotgg/uploadthing/issues/799

not a single interaction on that issue and no-one's been asking for it, so it just haven't been prioritized yet

**Closed by juliusmarminge** 2024-12-04 18:21 UTC
Labels: planned, ✨ enhancement
