### ISSUE TITLE
[Bug]: Infinite Redirect

### ISSUE THREAD

**Issue by anuragstudent** [pingdotgg/uploadthing#1069] opened 2024-11-27 03:02 UTC
### What happened?

I logged my account my github and now I am getting infinite redirect from https://uploadthing.com/dashboard/[username]-personal-team to https://uploadthing.com/link-team indefinitely 

### What did you expect to happen?

Not go in redirect loop, off course 

### Version

web version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment] 2024-11-27 14:02
I found what I think was the cause. Fixed and monitoring. Will leave this issue open for a bit before closing in case others are still experiencing issues

**Comment by anuragstudent** [comment] 2024-11-28 03:04
Sure but I didn't changed GitHub account or anything it just started to redirect out of nowhere

**Comment by juliusmarminge** [comment] 2024-11-28 10:01
Got it. We had a few users who didn't get a membership in their new team but that's been backfilled and should all have access now!

**Closed by juliusmarminge** 2024-11-28 10:02 UTC
Labels: area:dashboard, bug: high priority, status: monitoring

**Comment by lapiselazul** [comment] 2025-05-18 07:09
This also happened to me just 2 minutes ago from the time of this message. I had to manually enter the home page again on the same tab in order to get the message "team created successfully", otherwise the network tab was full of looping calls.
