### ISSUE TITLE
[Bug]: Throwing custom error in middleware causes server and components to crash

### ISSUE THREAD

**Issue by slyguy5646** [pingdotgg/uploadthing#218] opened 2023-07-16 03:32 UTC
### What happened?

Hey there. I'm using the base uploadthing example in a Next.js 13 project in the app router. I'm having some issues when throwing my own error from the upload middleware.

```TypeScript 

  freeUploader: f({ pdf: { maxFileSize: "128MB" } })
    .middleware(async ({ req }) => {
      // Checking auth via clerk
      const auth = getAuth(req);
      const token = await auth.getToken();
      // throwing error if not authenticated
      if (!auth.userId || !token) throw new Error("Unauthorized");


      // checking amount of user docs
      const previousDocs = await prisma.document.count({
        where: { user_id: auth.userId },
      });
     // throwing error if they've passed the limit
      if (previousDocs >= 3) {
        throw new Error("You've reached your free 3 document limit!");
      }

      return { auth, token };
    })
    .onUploadComplete(async ({ metadata, file }) => {
      console.log("Upload complete for userId:", metadata.auth.userId);

      console.log("file url", file.url);
      // handling db stuff
      createNewDocument(metadata.auth.userId, file, metadata.token);
    }),


```

### Clerk Middleware 

```TypeScript 
import { NextResponse } from "next/server";
import { authMiddleware } from "@clerk/nextjs/server";

export default authMiddleware({
  // Public routes are routes that don't require authentication
  publicRoutes: [
    "/",
    "/api(.*)",
  ],
  async afterAuth(auth, req) {
    if (auth.isPublicRoute) {
      return NextResponse.next();
    }

    const url = new URL(req.nextUrl.origin);

    if (!auth.userId) {
      
      url.pathname = "/sign-in";
      return NextResponse.redirect(url);
    }
  },
});

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api)(.*)"],
};
```

Above you can see I throw 2 errors of my own for 2 different scenarios and my Clerk middleware allows any request to the `/api` route. But, I'm running into errors.

On the client I get the `Failed to get presigned URLs` error rather than my custom message. Also, after refreshing the page and trying to upload another document, the dropzone component is stuck in the loading state. This loading state also causes the rest of the server/page to hang and freeze up.
![image](https://github.com/pingdotgg/uploadthing/assets/99554127/58a569de-37cd-410e-8097-fa82eb6611f9)

This is the first time I've seen this occur as I've had no easy way to test the unauthenticated error.

### What did you expect to happen?

During this test I expected my own error, `You've reached your free 3 document limit!`, in the uploadthing router handler to be thrown due to the given user's document limit being exceeded. 

### Version

5.1.0

### Reproduction Steps

As far as I can tell, this error can be reproduced by throwing an error in the middleware. 

### Reproduction Repository

I don't have a reproduction readily available but can create one if necessary.

### Relevant log output

```bash
[UT] UploadThing dev server is now running!
[UT] UploadThing dev server is now running!
DOC COUNT 3
[UT] middleware failed to run
Error: You've reached your free 3 document limit!
    at Object.eval [as middleware] (webpack-internal:///(sc_server)/./src/app/api/uploadthing/core.ts:35:19)
    at async eval (webpack-internal:///(sc_server)/../../node_modules/uploadthing/dist/next.mjs:249:30)
    at async POST (webpack-internal:///(sc_server)/../../node_modules/uploadthing/dist/next.mjs:326:26)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:265:37)
[UT] UploadThing dev server is now running!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment] 2023-07-17 17:25
This should have been fixed in `v5.2` with the new `errorFormatter` allowing you to customize what is returned to the client.

However, there seem to be a small regression of the new `errorFormatter` when throwing errors in middleware as that call wasn't wrapped in a try-catch block, causing the entire API request to throw early.

Fixed in #221 (see that PR for a canary you can use in the interim), after that you should be able to return your error with an [error formatter](https://docs.uploadthing.com/errors#error-formatting).

**Closed** 2023-07-17 19:02 UTC
Labels: bug

**Comment by slyguy5646** [comment] 2023-07-17 21:05
@juliusmarminge are you able to provide a usage example? The docs just show definition and my code still has the same error with the new canary. Probably something I'm doing wrong.

I updated my `createUploadThing` definition:

```TypeScript

const f = createUploadthing({
  errorFormatter: (err) => {
    return {
      message: err.message,
      zodError: err.cause instanceof z.ZodError ? err.cause.flatten() : null,
    };
  },
});
```

I'm throwing my custom errors the same way. Should I be throwing them differently?

**Comment by juliusmarminge** [comment] 2023-07-17 22:00
> @juliusmarminge are you able to provide a usage example? I don't get the same crash problem of the client/server but I don't get my custom error message on the client.
> 
> I updated my `createUploadThing` definition:
> 
> ```ts
> const f = createUploadthing({
>   errorFormatter: (err) => {
>     return {
>       message: err.message,
>       zodError: err.cause instanceof z.ZodError ? err.cause.flatten() : null,
>     };
>   },
> });
> ```
> 
> I'm throwing my custom errors the same way. Should I be throwing them differently and/or catching them in a special way?

So the above error formatter only adds the cause if it's a ZodError. The error you threw are not ZodErrors, so you'll get `null` in that check. You need to modify it so that it matches the `cause`'s that you want to return to the clietn.

**Comment by slyguy5646** [comment] 2023-07-18 21:35
Gotcha. Thanks!
