### ISSUE TITLE
[bug]: can't upload file to uploadthing

### ISSUE THREAD

**Issue by williamlin0518** [pingdotgg/uploadthing#385] opened 2023-09-23 18:42 UTC
### Provide environment information

```bash
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 15.94 GB / 31.75 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @uploadthing/react: ^5.6.1 => 5.6.1
    typescript: 5.2.2 => 5.2.2
    uploadthing: ^5.6.1 => 5.6.1

(base)
```

### Describe the bug

can't upload file to uploadthing

<img width="255" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/76b89c0e-623d-4840-acab-17540822c004">

after I click upload button, I got error and I log error.cause
<img width="625" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/5f1e8193-ae3b-4543-9349-eab6218ca438">

### Link to reproduction

 https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-appdir

### To reproduce

just use default code in  reproduction template https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-appdir

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment] 2023-09-24 18:09
Stackblitz uses deprecated Node 16 which has known issues. Can you test it out locally and make sure you're using Node 18?

```sh
npx degit pingdotgg/uploadthing/examples/minimal-appdir ut-test
```

For me it works just fine.

**Comment by williamlin0518** [comment] 2023-09-25 20:42
after I run npx degit pingdotgg/uploadthing/examples/minimal-appdir ut-test and use node18 ,still got error
<img width="336" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/be0f4f2b-1b8b-4ea1-a26d-4dc3228885d4"> 

<img width="412" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/5fb56f9f-66ee-4dbb-b34f-d347650b1f1e">

**Comment by juliusmarminge** [comment] 2023-09-25 22:30
Can you show network tab what tjd 400 request returns?

**Comment by williamlin0518** [comment] 2023-09-26 05:52
<img width="309" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/adce7fe4-8a91-49b7-a397-7e2a713c4909">
<img width="204" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/80030403/768cf7d2-ce28-4501-addb-a1b55fabf0e5">

**Comment by juliusmarminge** [comment] 2023-09-26 07:22
Sorry for the confusion, but I need to see the response json

![CleanShot 2023-09-26 at 09 21 40@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/b55fac87-8413-4f5c-9e62-8336e353f6cf)

**Comment by NoFearInMyHeart** [comment] 2023-10-02 01:54
<img width="1686" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/04baee13-988f-487c-b7eb-2c169839f467">
<img width="1166" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/f86aeb84-810f-4e37-85b9-26465e7eb990">
<img width="1191" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/4e230c4a-b4f1-40ca-8fe2-f538af937902">
<img width="1762" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/035cb29e-da62-4d3f-af16-f2d8127f7988">


I have the same problem, here is a screenshot of the http request

**Comment by juliusmarminge** [comment] 2023-10-02 06:08
> <img width="1686" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/04baee13-988f-487c-b7eb-2c169839f467">
> 
> <img width="1166" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/f86aeb84-810f-4e37-85b9-26465e7eb990">
> 
> <img width="1191" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/4e230c4a-b4f1-40ca-8fe2-f538af937902">
> 
> <img width="1762" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/035cb29e-da62-4d3f-af16-f2d8127f7988">
> 
> 
> 
> 
> 
> I have the same problem, here is a screenshot of the http request

That look concerning (500 without any response body). Can you provide a reproduction repo, and make sure to use Node ^18.13, please.

**Comment by NoFearInMyHeart** [comment] 2023-10-04 15:24
<img width="1791" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/5b85a950-93ed-4a60-a98a-051b6c37c4e3">
<img width="1777" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/ea8ae8b5-faa7-4da6-b7b5-4780fbfd5a6b">
<img width="1792" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/e29e647f-3633-4b51-b6f5-6dc68808a0a9">
<img width="1786" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/d6c293a2-85ee-4ea7-9f9f-f09f1054ba11">
<img width="597" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/086d3594-f06b-47c8-9c79-d6194409d3dc">
<img width="486" alt="image" src="https://github.com/pingdotgg/uploadthing/assets/29700967/d7323ad1-9366-4246-86c4-c61f1e17fab5">

I has updated next to the latest version 13.5.4

**Comment by juliusmarminge** [comment] 2023-10-05 08:46
<img alt="image" width="1792" src="https://user-images.githubusercontent.com/29700967/272625936-e29e647f-3633-4b51-b6f5-6dc68808a0a9.png"> 
It looks like you don't get a valid json response. Do you get any server logs?

I added a fix for the error you were getting that the response stream was already read here: `pnpm add uploadthing@5.7.2-canary.b992612`. I don't think that will fix everything for you though

**Comment by Grapeve** [comment] 2023-10-08 11:29
> <img alt="image" width="1686" src="https://user-images.githubusercontent.com/29700967/271867514-04baee13-988f-487c-b7eb-2c169839f467.png"> <img alt="image" width="1166" src="https://user-images.githubusercontent.com/29700967/271867551-f86aeb84-810f-4e37-85b9-26465e7eb990.png"> <img alt="image" width="1191" src="https://user-images.githubusercontent.com/29700967/271867628-4e230c4a-b4f1-40ca-8fe2-f538af937902.png"> <img alt="image" width="1762" src="https://user-images.githubusercontent.com/29700967/271867652-035cb29e-da62-4d3f-af16-f2d8127f7988.png">
> I have the same problem, here is a screenshot of the http request

I have the same problem too. I think this is a domestic network problem. Have you fixed it?

**Comment by markflorkowski** [comment] 2023-10-18 22:42
Closing this since there haven't been any replies since last week. Feel free to reopen if you are still encountering this issue on the latest version of uploadthing 👍

**Closed by markflorkowski** 2023-10-18 22:42 UTC
Labels: 🐛 bug: unconfirmed, area:packages
