### ISSUE TITLE
[Bug]: You can sign up with email, but can't login with email

### ISSUE THREAD

**Issue by michaelmannucci** [pingdotgg/uploadthing#238] opened 2023-08-01 12:17 UTC
### What happened?

I signed up with an email account from the link from the docs, but now cannot login to that account as Github is the only option.

### What did you expect to happen?

That I could login lol

### Version

The website itself

### Reproduction Steps

1. Go to sign-up page (this one specifically https://accounts.uploadthing.com/sign-up?redirect_url=https%3A%2F%2Fuploadthing.com%2Fdashboard)
2. sign-up with email
3. log out
4. never get in again 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment] 2023-08-01 19:51
Oh.. hm. That shouldn't be an option. You should only be able to sign up/in with a github account. I'll get that fixed today.

Did you lose access to any apps when this happened? If so, I can link them to a new account if you sign up with a GH account. DM me on Discord (`@markr`) with the email address you initially signed up with if you need me to do this 👍

**Comment by Balbalnom** [comment] 2023-08-01 22:12
> Oh.. hm. That shouldn't be an option. You should only be able to sign up/in with a github account. I'll get that fixed today.
> 
> Did you lose access to any apps when this happened? If so, I can link them to a new account if you sign up with a GH account. DM me on Discord (`@markr`) with the email address you initially signed up with if you need me to do this 👍

This might be a different issue or relate to the latest commit. I cannot login-in through the sign in portal.

What happened?
Try to sign in with Github

What did you expect to happen?
Cannot login with github account.


Version: 49569dd2401af44bcd208e1df9f775a7bcc98e6c

Reproduction Steps:
Go to sign-up page (https://uploadthing.com/sign-in)
sign-in with Github
It redirect me to sign-in page after the github SSO. : <

**Comment by MenroMi** [comment] 2023-08-02 13:38
> > Oh.. hm. That shouldn't be an option. You should only be able to sign up/in with a github account. I'll get that fixed today.
> > Did you lose access to any apps when this happened? If so, I can link them to a new account if you sign up with a GH account. DM me on Discord (`@markr`) with the email address you initially signed up with if you need me to do this 👍
> 
> This might be a different issue or relate to the latest commit. I cannot login-in through the sign in portal.
> 
> What happened? Try to sign in with Github SSO
> 
> What did you expect to happen? Cannot login with github account.
> 
> Version: [49569dd](https://github.com/pingdotgg/uploadthing/commit/49569dd2401af44bcd208e1df9f775a7bcc98e6c)
> 
> Reproduction Steps: Go to sign-up page (https://uploadthing.com/sign-in) sign-in with Github It redirect me to sign-in page after the github SSO. : < ![image](https://user-images.githubusercontent.com/7732520/257687587-ac864a9e-3110-413a-bb84-7f87423b1374.png)

I have the same problem. When i try login by github app redirect me to sign in page and that's all. Only what i have that information about redirect in address bar.

**Comment by markflorkowski** [comment] 2023-08-02 16:21
I can't seem to reproduce the sign in issues you are seeing @Balbalnom @MenroMi 

Can you try in an incognito tab/with extensions disabled?

What browsers are you using? Do you have an adblocker?

**Comment by MenroMi** [comment] 2023-08-02 17:01
> I can't seem to reproduce the sign in issues you are seeing @Balbalnom @MenroMi
> 
> Can you try in an incognito tab/with extensions disabled?
> 
> What browsers are you using? Do you have an adblocker?

In incognito i also have the same problem. Browser and version: Google chrome Version 114.0.5735.198 (Official Build) (arm64).

**Comment by markflorkowski** [comment] 2023-08-02 17:07
Can you check the network console to see if there is a request that is failing?

**Comment by MenroMi** [comment] 2023-08-02 17:20
<img width="1024" alt="Untitled" src="https://github.com/pingdotgg/uploadthing/assets/97913944/63542a6f-fbbb-498e-93a7-2fdd88f245dc">

**Comment by Balbalnom** [comment] 2023-08-02 17:21
> Can you check the network console to see if there is a request that is failing?

nope. All request looking good. 
![image](https://github.com/pingdotgg/uploadthing/assets/7732520/4eb7d11f-d9a0-4f13-b08f-342c9bbd7991)

Chrome: 115.0.5790.114 (Official Build) (x86_64)

**Comment by markflorkowski** [comment] 2023-08-02 17:21
Can you enable "preserve log" and try again?

**Comment by MenroMi** [comment] 2023-08-02 17:25
Nothing special with it property
<img width="1024" alt="Untitled" src="https://github.com/pingdotgg/uploadthing/assets/97913944/b735652b-0607-40df-af5e-2609ee7c0908">

**Comment by Balbalnom** [comment] 2023-08-02 17:25
> Can you enable "preserve log" and try again?

![image](https://github.com/pingdotgg/uploadthing/assets/7732520/4e386ac3-0530-49d9-a17d-3c951ce11088)
Here you go. I disabled all extensions and it is a fresh instance in chrome.

**Comment by markflorkowski** [comment] 2023-08-02 17:27
Your redirect URL is pointing at `/auth/sso`?

![image](https://github.com/pingdotgg/uploadthing/assets/11494384/8dc72c25-f121-4b4b-bf08-0fae7c7b7a71)

**Comment by MenroMi** [comment] 2023-08-02 17:35
> 

Yes, but authorization is not completed. But it turns out that the account itself is logging in, i guess.

**Comment by markflorkowski** [comment] 2023-08-02 17:36
Yeah, I am not seeing either of your accounts being created in Clerk. Debugging with the team now, will report back when I have some more info or steps to try!

**Comment by markflorkowski** [comment] 2023-08-02 17:51
@Balbalnom @MenroMi  Try logging in again now?

**Comment by Balbalnom** [comment] 2023-08-02 17:53
I can login now. Thanks!

**Comment by MenroMi** [comment] 2023-08-03 06:17
> @Balbalnom @MenroMi Try logging in again now?

I can also. Thanks.

**Comment by juliusmarminge** [comment] 2023-10-21 14:05
Pretty sure this should be fixed with recent dashboard refactor. Reopen if you experience this again

**Closed by juliusmarminge** 2023-10-21 14:05 UTC
Labels: bug, in progress
