### ISSUE TITLE
[bug]: [UT] unable to get presigned urls

### ISSUE THREAD

**Issue by EmmanuelKeifala** [pingdotgg/uploadthing#508] opened 2023-12-07 10:50 UTC
### Provide environment information

```bash
System:
    OS: macOS 12.7.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 18.94 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    Watchman: 2023.09.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @uploadthing/react: ^6.0.2 => 6.0.2 
    typescript: 5.3.2 => 5.3.2 
    uploadthing: ^6.0.4 => 6.0.4
```

### Describe the bug

I just can upload a file, but certain files of the same type uploads 

### Link to reproduction

https://github.com/EmmanuelKeifala/COM-LMS

### To reproduce

You have to be logged in as an uploader, and try to upload any file under the Attachments and Resources. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment] 2023-12-08 20:08
Can you try logging the error.cause() using the [error formatter](https://docs.uploadthing.com/errors)? (there is more info on the err.cause which isnt sent to client by default)

**Comment by EmmanuelKeifala** [comment] 2023-12-08 20:52
It just the same thing. The site was up and running, everything was perfect, until yesterday the codebase was not updated, nothing was changed

**Comment by markflorkowski** [comment] 2023-12-09 01:30
That doesn't make sense. The `error.cause`  that is thrown with that message should only be able to be either JSON or another error message.

**Comment by EmmanuelKeifala** [comment] 2023-12-09 01:44
here is the file router
export const ourFileRouter = {
  courseImage: f({image: {maxFileSize: '4MB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  courseAttachment: f({'application/pdf': {maxFileSize: '16GB'}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  chapterVideo: f({video: {maxFileCount: 1, maxFileSize: '512GB'}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
} satisfies FileRouter;

**Comment by markflorkowski** [comment] 2023-12-09 23:11
My bad, I meant the instantiation of the router eg:
```
const f = createUploadthing(...);
```

**Comment by EmmanuelKeifala** [comment] 2023-12-09 23:22
> My bad, I meant the instantiation of the router eg:
> 
> ```
> const f = createUploadthing(...);
> ```

import {createUploadthing, type FileRouter} from 'uploadthing/next';

const f = createUploadthing();

I noticed something if i compress the files to as little as 3mb i can upload
But then i checked on my dashboard, i have only used 8% of the given space, also i increased the default filesize

**Comment by markflorkowski** [comment] 2023-12-10 00:08
> const f = createUploadthing();

There is no errorParser defined here. Please add one to log `error.cause`

Here are the docs on the [error formatter](https://docs.uploadthing.com/errors)

**Comment by EmmanuelKeifala** [comment] 2023-12-10 06:59
> Here are the docs on the [error formatter](https://docs.uploadthing.com/errors)

const f = createUploadthing({
  errorFormatter: err => {
    return {
      message: err.message,
      zodError: err.cause instanceof z.ZodError ? err.cause.flatten() : null,
    };
  },
});

when i console log `console.log('Error Cause: ', error.data?.zodError);`
Error Cause:  null

if i console log the whole error i get this
![Screenshot 2023-12-10 at 6 58 51 AM](https://github.com/pingdotgg/uploadthing/assets/54929076/4df470a9-e71d-4962-8410-a59b27bdc292)

**Comment by markflorkowski** [comment] 2023-12-10 22:43
Try changing to 

```zodError: err.cause instanceof z.ZodError ? err.cause.flatten() : error.cause,```

**Comment by EmmanuelKeifala** [comment] 2023-12-10 22:57
> Try changing to
> 
> `zodError: err.cause instanceof z.ZodError ? err.cause.flatten() : error.cause,`

I still get the same errors man.
What is confusing is, if i compress the files to 3mb  it works perfectly. And 3mb is the max it can take

**Comment by MathiasGruber** [comment] 2023-12-11 18:03
I'm getting these errors suddenly as well now. Things were working 1-2 weeks ago when I was last working with my codebase, nothing significantly changed since then

**Comment by juliusmarminge** [comment] 2023-12-11 19:32
Try just logging the cause directly in the error formatter on the server.

```ts
const f = createUploadthing({
  errorFormatter: err => {
    console.log("error", err)
    console.log("cause", err.cause)
    return {
      message: err.message,
    };
  },
});
```

It should tell you why the request to UT failed.

**Comment by juliusmarminge** [comment] 2023-12-11 21:29
Okay so following that stack trace looks like you're uploading more files than allowed.

![CleanShot 2023-12-11 at 22 28 28@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/2259ba22-5e69-4e19-bfe6-1106e38695de)

I think @markflorkowski has already improved the error message here and will be released along with the next release

**Comment by EmmanuelKeifala** [comment] 2023-12-11 21:33
> ![CleanShot 2023-12-11 at 22 28 28@2x](https://private-user-images.githubusercontent.com/51714798/289676504-2259ba22-5e69-4e19-bfe6-1106e38695de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzA0OTYsIm5iZiI6MTcwMjMzMDE5NiwicGF0aCI6Ii81MTcxNDc5OC8yODk2NzY1MDQtMjI1OWJhMjItNWU2OS00ZTE5LWJmZTYtMTEwNmUzODY5NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIxMjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2N2RiOThkYTQ1ZWYxMWRlZDFjMGNmYjllNGVlMjM0MjkxNzA1YmZmMTVmN2U0YzcwYzE3OTRlNDM4Y2Y5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ue1YUp95X8kEC8u47rs91SoZoNx_jqQ_IS7iufWPcHk)
> 
> I think @markflorkowski has already improved the error message here and will be released along with the next release

So this means, every file extension have a limit to it upload ie you can only upload a certain number of pdfs even if you have more space on uploadthing

**Comment by EmmanuelKeifala** [comment] 2023-12-11 22:06
![Screenshot 2023-12-11 at 10 02 38 PM](https://github.com/pingdotgg/uploadthing/assets/54929076/07c6da1d-035b-47b1-ba0b-d6a9d4259640)

> If not specified in your file router, `maxFileCount` will [default to 1](https://docs.uploadthing.com/api-reference/server#defaults).

Sorry but I want to get this clearly, from the error code @markflorkowski wrote suggests to me that you can only upload a certain number of files of a given file type.
Except I am misunderstand what `maxFileCount` is, to my knowledge it is just how many files you can upload at once.

**Comment by markflorkowski** [comment] 2023-12-11 22:57
You specify maxFileCount in your fileRouter on a per-type and per-endpoint basis. This applies to each request

Eg for your router that [you shared above](https://github.com/pingdotgg/uploadthing/issues/508#issuecomment-1848077908), all of your endpoints would only accept a single file per request. I am assuming that you would want the `courseAttachment` route to actually accept multiple files at once, so you would need to specify that it can accept more than one. 

The error Julius showed is what should be returned if you try to upload eg. two files when your endpoint is only set to accept one.

**Comment by EmmanuelKeifala** [comment] 2023-12-11 23:10
```
export const ourFileRouter = {
  courseImage: f({image: {maxFileSize: '4MB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  courseAttachment: f({'application/pdf': {maxFileSize: '16GB', maxFileCount: 5,}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  chapterVideo: f({video: {maxFileSize: '512GB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
} satisfies FileRouter;
```
with the update I still get that error

**Comment by juliusmarminge** [comment] 2023-12-12 08:51
> with the update I still get that error

same stack trace?

**Comment by EmmanuelKeifala** [comment] 2023-12-12 09:07
```
error UploadThingError: Unable to get presigned urls
    at eval (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-TX4EGJ4S.mjs:457:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.POST (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-CFWCJEOQ.mjs:300:26)
    at async node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62609 {
  code: 'URL_GENERATION_FAILED',
  data: undefined,
  cause: undefined
}
```

**Comment by MathiasGruber** [comment] 2023-12-12 11:53
I get the same error: 
![image](https://github.com/pingdotgg/uploadthing/assets/7893509/fe54e4d1-3eca-469c-b492-14137bf1c352)

"@uploadthing/react": "6.0.2",
"uploadthing": "6.0.4"

**Comment by markflorkowski** [comment] 2023-12-12 22:04
@EmmanuelKeifala I cloned your repository and comfigured it locally, and I am not seeing any errors using this file router:
```ts
export const ourFileRouter = {
  courseImage: f({image: {maxFileSize: '4MB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  courseAttachment: f({'application/pdf': {maxFileSize: '16GB', maxFileCount: 5}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  chapterVideo: f({video: {maxFileSize: '512GB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
} satisfies FileRouter;
```

Tested by uploading 3 pdfs: 
![image](https://github.com/pingdotgg/uploadthing/assets/11494384/ceafd87b-9f68-4e66-8d07-bf49406137dd)


Does this only happen in production builds or also in dev? On a side note, I also noticed that you are only persisting the first file to DB when multiple are uploaded at once. Wouldn't have any effect on the errors, but just something I noticed.

**Comment by tinotendajoe01** [comment] 2023-12-14 09:39
I started to have this error this morning saying `[UT] unable to get pre-signed urls` then I followed this issue, and did some logs here are my 
```
const f = createUploadthing({
  errorFormatter: (err) => {
    console.log("error", err);
    console.log("cause", err.cause);
    return {
      message: err.message,
    };
  },
});
```
here is the output
<img width="285" alt="Screenshot 2023-12-14 at 11 01 03" src="https://github.com/pingdotgg/uploadthing/assets/60421124/e07a36a3-2962-4636-9cda-f2f01b1e4325">

 in the network tabs, it jumps from error 404, or 500. i am using UT free tier i even created a new project o see if its the quota issue got the same error again
 
here is a perfect report you can clone to reproduce the error   [GIT REPO](https://github.com/joschan21/quill), during pdf upload it throws this error

**Comment by juliusmarminge** [comment] 2023-12-14 09:57
> i am using UT free tier i even created a new project o see if its the quota issue got the same error again 

For free apps the quota is shared so once you've reached the 2GB, you'll have to upgrade the app to upload more files. Creating new free apps will not help as they contrivute to the same quota

**Comment by EmmanuelKeifala** [comment] 2023-12-16 22:42
> @EmmanuelKeifala I cloned your repository and comfigured it locally, and I am not seeing any errors using this file router:
> 
> Does this only happen in production builds or also in dev? On a side note, I also noticed that you are only persisting the first file to DB when multiple are uploaded at once. Wouldn't have any effect on the errors, but just something I noticed.


@markflorkowski can you please tell me what you did differently, because i have the same code sitting locally but i still log the same errors.

**Comment by markflorkowski** [comment] 2023-12-17 21:32
I literally just cloned it, set the env vars, ran a pnom install, then ran the dev server. Nothing special.

**Comment by EmmanuelKeifala** [comment] 2023-12-17 21:44
> I literally just cloned it, set the env vars, ran a pnpm install, then ran the dev server. Nothing special.

thanks man for all your effort can we try this, send some of my pdfs to you and you try uploading them. Then you also send yours?

**Comment by DemaPy** [comment] 2023-12-20 09:40
@EmmanuelKeifala today i also faced the same problem. **unable to get presigned urls**

I resolve that one by loading PDF files under 4MB. as i mentioned in my config. **f({ pdf: { maxFileSize: "4MB", maxFileCount: 1 } })**

**Comment by DemaPy** [comment] 2023-12-20 09:56
@markflorkowski could you please advice how to handle size error?

I have tried to do so like in docs.
![image](https://github.com/pingdotgg/uploadthing/assets/80632445/daba9579-4b86-4021-95dc-1c6c3d0463ff)
![image](https://github.com/pingdotgg/uploadthing/assets/80632445/a194737a-4d06-434e-9402-e33b39e844f0)
![image](https://github.com/pingdotgg/uploadthing/assets/80632445/d8aed124-ad7b-4d27-928c-9ddd4e118b5b)


But i still have an error: **unable to get presigned urls**
But i want to handle File size error.

**Comment by juliusmarminge** [comment] 2023-12-20 10:33
> @markflorkowski could you please advice how to handle size error?
> 
> I have tried to do so like in docs. ![image](https://private-user-images.githubusercontent.com/80632445/291851848-daba9579-4b86-4021-95dc-1c6c3d0463ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg1NTEsIm5iZiI6MTcwMzA2ODI1MSwicGF0aCI6Ii84MDYzMjQ0NS8yOTE4NTE4NDgtZGFiYTk1NzktNGI4Ni00MDIxLTk1ZGMtMWM2YzNkMDQ2M2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYWZkNzI3OTc0MDA0NGIyNjFhODExMGMyOTM5MGNjODUyYTcwMmI4MTRlMGQ1ZTVlOTVmNWFjZjg1ZjM4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NmnDHa9uxXzjntluuDqF9k1rzvWxZoPnHYvu9m0pNpk) ![image](https://private-user-images.githubusercontent.com/80632445/291851904-a194737a-4d06-434e-9402-e33b39e844f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg1NTEsIm5iZiI6MTcwMzA2ODI1MSwicGF0aCI6Ii84MDYzMjQ0NS8yOTE4NTE5MDQtYTE5NDczN2EtNGQwNi00MzRlLTk0MDItZTMzYjM5ZTg0NGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNTgzOTc0Yjc3MTRhMjBlMGU2ODgzYWYyOTc3NWYyYWE2ODFmOGExNDliYjNhZjNlYjIyMmQ4YmNlNzk2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vkmRYipG2yGR2K1hXXEzxgPzM9-Tdr0ACrHVzNrLXo) ![image](https://private-user-images.githubusercontent.com/80632445/291853794-d8aed124-ad7b-4d27-928c-9ddd4e118b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg1NTEsIm5iZiI6MTcwMzA2ODI1MSwicGF0aCI6Ii84MDYzMjQ0NS8yOTE4NTM3OTQtZDhhZWQxMjQtYWQ3Yi00ZDI3LTkyOGMtOWRkZDRlMTE4YjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzJjNmFjNTU2YjY5MzIzOWUwZmI0OGI4ZDE1N2EwNWYyZWE4MGE5YTdmZTEyODg3MzMxMmM1N2NiYmM5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRUia04v_QN0_8Zm4xXwqvfUvUjOYBpqsTjuTB3oOqQ)
> 
> But i still have an error: **unable to get presigned urls** But i want to handle File size error.

we'll get this part of error handling improved early 2024, we're focused on shipping multiregion and private files right now.

the tl;dr is we don't check the sizes locally on your server yet but this is only done on UT server, which limits the accuracy of errors we can give. i got a ticket to add this check to be part of the upload route on your server which would allow us to return a much better error of what file is too big or other route config mismatches.

**Comment by EmmanuelKeifala** [comment] 2024-01-05 17:03
Hy @markflorkowski, i just can't get around this problem
```
error UploadThingError: Unable to get presigned urls
    at eval (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-3K3M4GBL.mjs:457:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.POST (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/chunk-FHKHQWYO.mjs:303:26)
    at async /Users/mohamed/comahs-e/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62609 {
  code: 'URL_GENERATION_FAILED',
  data: undefined,
  cause: undefined
}
```
I can perfectly upload files that are below 4MB but not it
Here is how the `ourFileRouter` looks like
```
export const ourFileRouter = {
  courseImage: f({image: {maxFileSize: '4MB', maxFileCount: 1}})
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
  courseAttachment: f([
    'text',
    'image',
    'video',
    'audio',
    'pdf',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.ms-powerpoint.presentation.macroenabled.12',
  ])
    .middleware(() => handleAuth())
    .onUploadComplete(() => {}),
} satisfies FileRouter;
```

**Comment by markflorkowski** [comment] 2024-01-05 18:27
@EmmanuelKeifala Is this still for [this repo](https://github.com/EmmanuelKeifala/COM-LMS)?

I just cloned the latest from main again, applied your DB schema, and ran it without any issues locally and uploaded an 8MB pdf.  Are you having these issues in development or production?

**Comment by EmmanuelKeifala** [comment] 2024-01-07 19:21
> @EmmanuelKeifala Is this still for [this repo](https://github.com/EmmanuelKeifala/COM-LMS)?
> 
> I just cloned the latest from main again, applied your DB schema, and ran it without any issues locally and uploaded an 8MB pdf. Are you having these issues in development or production?

yes its the same repo, i really don't understand what's happening. I get the error in development and in production

**Comment by markflorkowski** [comment] 2024-01-08 18:51
Are you still getting this error today? I fixed a related bug over the weekend that could have possibly been affecting you.

**Comment by duc-hoang-161** [comment] 2024-01-10 20:44
I had the same error but I managed to make it work. 
- Upgraded to the newer version (6.1.0 -> 6.1.1), the error was still remain
- Created a new API key and replaced the old one => Worked

**Comment by markflorkowski** [comment] 2024-01-10 21:08
Huh... creating a new key should not have any effect 🤔

**Comment by duc-hoang-161** [comment] 2024-01-10 21:34
I retried using the old one and it works now, might be a cache issue somewhere when I upgrade the package

**Closed** 2024-01-10 21:49 UTC
Labels: 🐛 bug: unconfirmed, area:packages

**Comment by Nathan-Devery** [comment] 2025-01-19 01:48
Yay for breaking my code with your updates

**Comment by juliusmarminge** [comment] 2025-01-19 01:49
> Yay for breaking my code with your updates

What code broke?

**Comment by Nathan-Devery** [comment] 2025-01-19 02:49
*false alarm - transient error. I'm assuming there was some downtime.
